### ISSUE TITLE
Need help with using

### ISSUE THREAD

**Issue by artem-malko** [mkleehammer/gulp-deporder#2]
Hello.

I've got some problem with using your plugin. For example, i've got the same FS like in your second example in README. What should i write in // requires in models, if i'd like to order them from collection js-files?
// requires ../models/example.js is not working(

**Comment by m157y** [comment]
@artem-malko, sorry for late reply, but issue must be closed I think :)
Your mistake is that you writes `// requires ../models/example.js` instead of `// requires: ../models/examples.js` colon is important for current release. But last merged PR fixes this requirement. So all what we can do is wait for new release.

**Comment by mkleehammer** [comment]
Released.  Thanks so much.
